version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apollo-datasource-rest
    versions:
    - 0.10.0
    - 0.11.0
    - 0.9.7
